name: Running CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: build